version: "3.8"

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - application-network

  app:
    build: .
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ${PWD}/:/tmp/
    networks:
      - application-network

  webserver:
    image: nginx:1.23.4-alpine
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - application-network
    ports:
      - '7410:80'
    depends_on:
      - app
      - mysql

networks:
  application-network:
    name: application-network

volumes:
  mysql-data:
    name: mysql-data
